# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: kamz-agentpool

stages:
  - stage: "CI"
    jobs:
      - job: "Lint_Test"
        displayName: 'Run Lint test(s)'
        workspace:
          clean: all
        steps:
          - script: pip install -r requirements.txt
          - script: flake8 ui.py
      - job: "Unit_Test"
        displayName: 'Run Unit test(s)'
        workspace:
          clean: all        
        dependsOn: "Lint_Test"
        steps:
          - script: python test_calc.py
  - stage: "CD"
    dependsOn: "CI"
    jobs:
      - job: "Build_Release_Job"
        workspace:
          clean: all      
        displayName: "Build and Release the exe"
        steps:           
        - script: pip install -r requirements.txt
        - script: pyinstaller ui.py --onedir --name SimpleCalculator_CLI -y
        # - script: pyinstaller ui.py --onedir --name SimpleCalculator_CLI --clean -y
        - powershell: ls .\dist\SimpleCalculator_CLI
        - powershell: compress-archive -path '.\dist' -destinationpath '.\SimpleCalculator_CLI.zip' -compressionlevel optimal -Force

        - task: AzureFileCopy@4
          inputs:
            SourcePath: '.\SimpleCalculator_CLI.zip'
            azureSubscription: 'spn101'
            Destination: 'AzureBlob'
            storage: 'devsa3'
            ContainerName: 'simplecalculatorrelease'
