# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: kamz-agent

variables:
  rel_src_path: 

stages:
  - stage: "CI"
    jobs:
      - job: "Lint_Test"
        displayName: 'Run Lint test(s)'
        steps:
          - script: pip install -r requirements.txt
          - script: flake8 ui.py

      - job: "Unit_Test"
        displayName: 'Run Unit test(s)'
        dependsOn: "Lint_Test"
        steps:
          - script: python test_calc.py

  - stage: "CD"
    dependsOn: "CI"
    jobs:
      - job: "Build_Job"
        displayName: "Building the exe"
        steps:           
        - script: pip install -r requirements.txt
        - script: pyinstaller ui.py --onedir --name SimpleCalculator_CLI --clean --version-file=version.txt
        - powershell: pwd

      - job: "Release_Job"
        dependsOn: "Build_Job"
        displayName: "Releasing the exe to Storage Account"
        steps:
        - task: AzureFileCopy@4
          displayName: 'AzureBlob File Copy'
          inputs:
            SourcePath: .\dist\SimpleCalculator_CLI\SimpleCalculator_CLI.exe
            azureSubscription: 'KAMZ-sub-1 (0fddd6bc-7791-4071-8c37-13c244582193)'
            Destination: AzureBlob
            storage: devsa3
            ContainerName: release
