# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: kamz-agent

stages:
  - stage: "CI"
    jobs:
      - job: "Lint_Test"
        displayName: 'Run Lint test(s)'
        steps:
          - script: pip install -r requirements.txt
          - script: flake8 ui.py

      - job: "Unit_Test"
        displayName: 'Run Unit test(s)'
        dependsOn: "Lint_Test"
        steps:
          - script: python test_calc.py

  - stage: "CD"
    dependsOn: "CI"
    jobs:
      - job: "Build_Release_Job"
        displayName: "Build and Release the exe"
        steps:           
        - script: pip install -r requirements.txt
        - script: pyinstaller ui.py --onedir --name SimpleCalculator_CLI --clean --version-file=version.txt -y
        - powershell: ls .\dist\SimpleCalculator_CLI
        - task: AzureFileCopy@4
          inputs:
            SourcePath: '.\dist\SimpleCalculator_CLI\SimpleCalculator_CLI.exe'
            azureSubscription: 'spn101'
            Destination: 'AzureBlob'
            storage: 'devsa3'
            ContainerName: 'executable'      

        - task: AzureFileCopy@4
          inputs:
            SourcePath: '.\dist'
            azureSubscription: 'spn101'
            Destination: 'AzureBlob'
            storage: 'devsa3'
            ContainerName: 'totaldistro'  